# Filtering Pandas DataFrame

In [1]:
import numpy as np
import pandas as pd

#### 데이터 불러오기

In [2]:
df = pd.read_csv("Downloads/disney_plus_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,A Spark Story,"Jason Sterman, Leanne Dare","Apthon Corbin, Louis Gonzales",NaN,"September 24, 2021",2021,TV-PG,88 min,Documentary,Two Pixar filmmakers strive to bring their uni...
1,s2,Movie,Spooky Buddies,Robert Vince,"Tucker Albrizzi, Diedrich Bader, Ameko Eks Mas...","United States, Canada","September 24, 2021",2011,G,93 min,"Comedy, Fantasy, Kids",The puppies go on a spooky adventure through a...
2,s3,Movie,The Fault in Our Stars,Josh Boone,"Shailene Woodley, Ansel Elgort, Laura Dern, Sa...",United States,"September 24, 2021",2014,PG-13,127 min,"Coming of Age, Drama, Romance",Hazel and Gus share a love that sweeps them on...
3,s4,TV Show,Dog: Impossible,NaN,Matt Beisner,United States,"September 22, 2021",2019,TV-PG,2 Seasons,"Animals & Nature, Docuseries, Family",Matt Beisner uses unique approaches to modifyi...
4,s5,TV Show,Spidey And His Amazing Friends,NaN,"Benjamin Valic, Lily Sanfelippo, Jakari Fraser...",United States,"September 22, 2021",2021,TV-Y,1 Season,"Action-Adventure, Animation, Kids",Spidey teams up with pals to become The Spidey...
...,...,...,...,...,...,...,...,...,...,...,...,...
1363,s1364,Movie,The Sword in the Stone,Wolfgang Reitherman,"Sebastian Cabot, Karl Swenson, Rickie Sorensen...",United States,"October 1, 2019",1963,G,80 min,"Action-Adventure, Animation, Comedy",Merlin trains a young orphan who's destined to...
1364,s1365,Movie,Those Calloways,Norman Tokar,"Brian Keith, Vera Miles, Brandon de Wilde, Wal...",United States,"October 1, 2019",1965,PG,132 min,"Animals & Nature, Drama, Family",A strong-willed family struggles to establish ...
1365,s1366,TV Show,Disney Kirby Buckets,NaN,"Jacob Bertrand, Mekai Curtis, Cade Sutton, Oli...",United States,NaN,2014,TV-Y7,3 Seasons,"Action-Adventure, Comedy, Coming of Age",Welcome to Kirby's world! It's rude and sketchy.
1366,s1367,TV Show,Disney Mech-X4,NaN,"Nathaniel Potvin, Raymond Cham, Kamran Lucas, ...",Canada,NaN,2016,TV-Y7,2 Seasons,"Action-Adventure, Comedy, Science Fiction",Ryan discovers his ability to control a giant ...
1367,s1368,TV Show,Imagination Movers,NaN,"Rich Collins, Dave Poche, Scott Durbin, Scott ...",United States,NaN,2008,TV-Y,3 Seasons,"Kids, Music","Rock out with the Imagination Movers, Disney J..."

#### isna( ) 함수를 통해 Null 값 확인

In [3]:
df.isna().mean()

show_id         0.000000
type            0.000000
title           0.000000
director        0.321637
cast            0.127193
country         0.127924
date_added      0.002193
release_year    0.000000
rating          0.001462
duration        0.000000
listed_in       0.000000
description     0.000000
dtype: float64

#### dropna( ) 함수를 통해 Null 값 제거

In [4]:
# null 값 제거 
df.dropna(inplace =True, axis=0)
df.isna().mean()

show_id         0.0
type            0.0
title           0.0
director        0.0
cast            0.0
country         0.0
date_added      0.0
release_year    0.0
rating          0.0
duration        0.0
listed_in       0.0
description     0.0
dtype: float64

### 단일조건 필터링
*   DataFrame명[ DataFrame명 ['칼럼명']   값]

In [5]:
year = df['release_year'] >2020
df[year].head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
19,s20,Movie,Twenty Something,Aphton Corbin,"Kaylin Price, Ariana Brown, Aliyah Taylor, Jan...",United States,"September 10, 2021",2021,PG,11 min,"Animation, Family","Adulting is hard. One day you're nailing it, t..."

In [6]:
df[df['release_year'] > 2020].tail(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
214,s215,Movie,Flora & Ulysses,Lena Khan,"Matilda Lawler, Alyson Hannigan, Ben Schwartz,...",United States,"February 19, 2021",2021,PG,95 min,"Comedy, Coming of Age, Drama",Comic book fan Flora saves a squirrel whose su...

### 복합조건 필터링 
* Numpy variants 사용 - np.logical_and , np.logical_or , np.logical_not

In [7]:
df[np.logical_and(df['country'] == 'United States', df['release_year'] > 2020 )].head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
19,s20,Movie,Twenty Something,Aphton Corbin,"Kaylin Price, Ariana Brown, Aliyah Taylor, Jan...",United States,"September 10, 2021",2021,PG,11 min,"Animation, Family","Adulting is hard. One day you're nailing it, t..."
24,s25,Movie,Happier Than Ever: A Love Letter to Los Angeles,"Robert Rodriguez, Patrick Osborne","Billie Eilish, FINNEAS",United States,"September 3, 2021",2021,TV-14,66 min,"Concert Film, Music","Billie Eilish makes her Disney+ debut with ""Ha..."

### & 사용
DataFrame명[(DataFrame명['칼럼명1'] 값) & (DataFrame명['칼럼명2']  값)]

In [8]:
 df[(df['country'] == 'United Kingdom' ) &  (df['release_year'] >2018)].tail(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
539,s540,Movie,Viking Warrior Women,Stuart Strickson,Ella Al-Shamahi,United Kingdom,"February 28, 2020",2019,TV-PG,44 min,"Documentary, Historical",New discoveries challenge everything we though...
1229,s1230,Movie,The Lost Tomb of Alexander the Great,Duncan Singh,Matt McFetridge,United Kingdom,"November 12, 2019",2019,TV-PG,44 min,"Documentary, Historical",An archaeologist on the hunt for Alexander the...

### Query 함수 사용 필터링 
* 조건에 부합하는 데이터 추출 
* 문법 사용 예   
  DataFrame.query('(a < b) & (b < c) ')  
  DataFrame.query(' a < b  &  b < c' )  
  DataFrame.query(' a < b  and b < c')  
  DataFrame.query(' a < b < c ')

In [9]:
df.query('release_year > 2019  & release_year > 2020 ').tail(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
207,s208,Movie,Myth: A Frozen Tale,Jeff Gipson,Evan Rachel Wood,United States,"February 26, 2021",2021,TV-G,12 min,"Animation, Family, Fantasy",A family sits down for a bedtime story and is ...
214,s215,Movie,Flora & Ulysses,Lena Khan,"Matilda Lawler, Alyson Hannigan, Ben Schwartz,...",United States,"February 19, 2021",2021,PG,95 min,"Comedy, Coming of Age, Drama",Comic book fan Flora saves a squirrel whose su...